# backend/headings.py

ALL_HEADINGS = [
    "DEPARTMENTAL ACTIVITIES:",
    "GUEST LECTURES – DELIVERED BY THE FACULTY:",
    "GUEST LECTURE/S – INVITED:",
    "FACULTY PUBLICATIONS IN (NATIONAL / INTERNATIONAL) JOURNALS:",
    "FACULTY PUBLICATIONS IN (NATIONAL / INTERNATIONAL) CONFERENCES:",
    "FACULTY ACHIEVEMENTS:",
    "FUNDED PROJECTS:",
    "PATENTS:",
    "STUDENT PUBLICATIONS:",
    "STUDENT ACHIEVEMENTS:",
    "PLACEMENT AND HIGHER STUDIES RECORD:",
    "TECHNICAL ARTICLES:",
]

# Sections that OWN tables (tables may span pages)
TABLE_SECTIONS = {
    "FACULTY PUBLICATIONS IN (NATIONAL / INTERNATIONAL) JOURNALS:",
    "FACULTY PUBLICATIONS IN (NATIONAL / INTERNATIONAL) CONFERENCES:",
    "STUDENT PUBLICATIONS:",
    "STUDENT ACHIEVEMENTS:",
    "PLACEMENT AND HIGHER STUDIES RECORD:",
    "FUNDED PROJECTS:",
    "PATENTS:",
}

def normalize_heading(text: str):
    text = text.strip()
    for h in ALL_HEADINGS:
        if text.upper() == h.upper():
            return h
    return None